version: '3'

services:
  app_gestor:
    build: gestor
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://guada_app:3306/guada?useSSL=false&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: hb0fhnfc
    restart: always
    depends_on:
      db_gestor:
          condition: service_healthy

  db_gestor:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hb0fhnfc
      MYSQL_PASSWORD: hb0fhnfc
      MYSQL_DATABASE: guada
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
